config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

match 'groups/enable_to_read_groups/:id', :controller => 'groups', :action => 'enable_to_read_groups', :id => /\d+/, :via => :post
match 'groups/disable_to_read_groups/:id', :controller => 'groups', :action => 'disable_to_read_groups', :id => /\d+/,  :via => :post
match 'groups/enable_reader_group/:id', :controller => 'groups', :action => 'enable_reader_group', :id => /\d+/, :via => :post
match 'groups/disable_reader_group/:id', :controller => 'groups', :action => 'disable_reader_group', :id => /\d+/,  :via => :post


match 'journals/change_allowed_readers/:id', :controller => 'journals', :action => 'change_allowed_readers', :id => /\d+/,  :via => [:post, :put]

app/views/groups/_groups_allowed_author.html.erb
<div class="splitcontentleft">
<% if @group.allowed_groups_authors.any? %>
<table class="list groups">
  <thead><tr>
  <th><%=l(:label_group)%></th>
  <th><%=l(:label_user_plural)%></th>
  <th style="width:15%"></th>
  </tr></thead>
  <tbody>
  <% @group.allowed_groups_authors.each do |comment_author_group| %>
  <% next if comment_author_group.new_record? %>
  <tr id="group-<%= comment_author_group.id %>" class="<%= cycle 'odd', 'even' %> class">
	<td><%= link_to h(comment_author_group), edit_group_path(comment_author_group) %></td>
	<td align="center"><%= comment_author_group.users.size %></td>
	<td class="buttons">
    <%= delete_link({:controller => 'groups', :action => 'disable_to_read_groups', :id => @group, :author_group_id => comment_author_group},
	                      :remote => true,
	                      :method => :post) %> 
	</td>
  </tr>
<% end; reset_cycle %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<div class="splitcontentright">
<% author_groups = @group.not_in_available_authors.all(:limit => 100) %>
<% if author_groups.any? %>
	<%= form_for(:group, :remote => true, :url => { :action => 'enable_to_read_groups', :id => @group }) do %>
		<%= label_tag "available_author_groups", l(:description_choose_author_groups), :class => "hidden-for-sighted" %>
      	<%= principals_check_box_tags 'author_group_ids[]', author_groups %>
		<p><%= submit_tag l(:button_add) %></p>
	<% end %>
<% end %>

</div>

app/views/groups/disable_to_read_groups.js.erb
$('#tab-content-groups_allowed_author').html('<%= escape_javascript(render :partial => 'groups/groups_allowed_author') %>');

app/views/groups/enable_to_read_groups.js.erb
$('#tab-content-groups_allowed_author').html('<%= escape_javascript(render :partial => 'groups/groups_allowed_author') %>');
<% @authors.each do |author| %>
  $('#group-<%= author.id %>').effect("highlight");
<% end %>

app/views/issues/_conflict.html.erb
<div class="conflict">
  <%= l(:notice_issue_update_conflict) %> 
  <% if @conflict_journals.present? %>
    <div class="conflict-details">
    <% @conflict_journals.sort_by(&:id).each do |journal| %>
      <p><%= authoring journal.created_on, journal.user, :label => :label_updated_time_by %></p>
      <% if journal.details.any? %>
      <ul class="details">
        <% details_to_strings(journal.details).each do |string| %>
         <li><%= string %></li>
        <% end %>
      </ul>
      <% end %>
      <%= textilizable(journal, :notes) unless journal.notes.blank? %>
    <% end %>
    </div>
  <% end %>
</div>
<p>
  <label><%= radio_button_tag 'conflict_resolution', 'overwrite' %> <%= l(:text_issue_conflict_resolution_overwrite) %></label><br />
  <% if @issue.notes.present? %>
  <label><%= radio_button_tag 'conflict_resolution', 'add_notes' %> <%= l(:text_issue_conflict_resolution_add_notes) %></label><br />
  <% end %>
  <label><%= radio_button_tag 'conflict_resolution', 'cancel' %> <%= l(:text_issue_conflict_resolution_cancel, :link => link_to_issue(@issue, :subject => false)).html_safe %></label>
</p>
<p><%= submit_tag l(:button_submit) %></p>

app/views/issues/_edit.html.erb
<%= labelled_form_for @issue, :html => {:id => 'issue-form', :multipart => true} do |f| %>
    <%= error_messages_for 'issue', 'time_entry' %>
    <%= render :partial => 'conflict' if @conflict %>
    <div class="box">
    <% if @edit_allowed || !@allowed_statuses.empty? %>
        <fieldset class="tabular"><legend><%= l(:label_change_properties) %></legend>
        <div id="all_attributes">
        <%= render :partial => 'form', :locals => {:f => f} %>
        </div>
        </fieldset>
    <% end %>
    <% if User.current.allowed_to?(:log_time, @project) %>
        <fieldset class="tabular"><legend><%= l(:button_log_time) %></legend>
        <%= labelled_fields_for :time_entry, @time_entry do |time_entry| %>
        <div class="splitcontentleft">
        <p><%= time_entry.text_field :hours, :size => 6, :label => :label_spent_time %> <%= l(:field_hours) %></p>
        </div>
        <div class="splitcontentright">
        <p><%= time_entry.select :activity_id, activity_collection_for_select_options %></p>
        </div>
        <p><%= time_entry.text_field :comments, :size => 60 %></p>
        <% @time_entry.custom_field_values.each do |value| %>
          <p><%= custom_field_tag_with_label :time_entry, value %></p>
        <% end %>
        <% end %>
    </fieldset>
    <% end %>

    <fieldset><legend><%= l(:field_notes) %></legend>
    <%= f.text_area :notes, :cols => 60, :rows => 10, :class => 'wiki-edit', :no_label => true %>
    <%= wikitoolbar_for 'issue_notes' %>

    <% if @issue.safe_attribute? 'private_notes' %>
    <label for="issue_private_notes"><%= f.check_box :private_notes, :no_label => true %> <%= l(:field_private_notes) %></label>
    <% end %>

    <%= call_hook(:view_issues_edit_notes_bottom, { :issue => @issue, :notes => @notes, :form => f }) %>
    </fieldset>

    <fieldset><legend><%= l(:label_attachment_plural) %></legend>
    <p><%= render :partial => 'attachments/form', :locals => {:container => @issue} %></p>
    </fieldset>
    </div>

    <%= f.hidden_field :lock_version %>
    <%= hidden_field_tag 'last_journal_id', params[:last_journal_id] || @issue.last_journal_id %>
    <%= submit_tag l(:button_submit) %>
    <%= preview_link preview_edit_issue_path(:project_id => @project, :id => @issue), 'issue-form' %>
<% end %>

<div id="preview" class="wiki"></div>

app/views/issues/_private_new_notes_bottom.html.erb
<div id="edit-readers-groups" >
	<p><%= l :private_comments_for_groups%></p>
	<p><% Group.all.each do |group| %>
		<%= check_box_tag 'group_ids[]', group.id, aDefGroups.include?(group)-%>
		<%= label_tag 'group_ids[]', group.name %>
		<br />
	<% end%></p>		
</div>

app/views/issues/_private_notes_bottom.html.erb
<div id="<%="bottom-note-#{journal.id}"%>" >
<% if User.current.allowed_to?(:manage_group_access_to_notes, @project)%>
<p style="text-align: right;">
	<em><%= l :private_comments_for_groups%></em>
</p>
	<div id="edit-readers-groups">
		<%= form_for(journal, :url => {:controller => 'journals', :action => 'change_allowed_readers', :id => journal.id }, :remote => true) do |f| %>
			<p><% journal.groups.each do |allow_group| %>
				<%= label_tag 'group_ids[]', allow_group.name %>
				<%= check_box_tag 'group_ids[]', allow_group.id, true %>
			<% end%></p>		
			-------------
			<p><% (Group.where("1=1") - journal.groups).each do |group| %>
				<%= label_tag 'group_ids[]', group.name %>
				<%= check_box_tag 'group_ids[]', group.id, false %>
			<% end%></p>		
			<p><%= submit_tag l(:button_save) %></p>		
		<% end%>
	</div>
<% end%>
</div>

app/views/journals/change_allowed_readers.js.erb
$('#<%= "bottom-note-#{@journal.id}"%>').html('<%= escape_javascript(render :partial => 'issues/private_notes_bottom', :locals => {:journal => @journal}) %>');